config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  post 'switch_mode', to: 'pages#switch_mode'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :mode
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def mode
    cookies[:dark_mode] == "true" ? @dark_mode = true : @dark_mode = false
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def switch_mode
    @dark_mode == true ? cookies.permanent[:dark_mode] = false : cookies.permanent[:dark_mode] = true
    redirect_to request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'logo.png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="<%= @dark_mode ? 'dark-mode' : 'light-mode' %>">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_client_testimonials.html.erb
<div class="carousel-item active">
  <div class="row m-0 testimonials-row">
    <div class="mid-line client-testimonials-line"></div>
    <div class="testimonial-card <%= @dark_mode ? 'dark-bg' : 'light-bg' %>">
      <div class="testimonial-image" style="background-image: url(<%= image_path 'fanning.png' %>)"></div>
      <div class="testimonial-content p-3">
        <div class="">
          <h3 class="mb-1">Ben Fanning</h3>
          <h5 class="pb-0 pb-md-3 testimonial-role">Founder at Hoxton Digital</h5>
        </div>
        <div class="">
          <div class="testimonial-message">
            <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote left-quote', alt: 'opening quote', alt: 'opening quote' %>
            <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote right-quote', alt: 'closing quote', alt: 'closing quote' %>
            <p class="mb-2">Ife was the first person I hired at Hoxton Digital and he is the first person I would hire if I started a new business tomorrow. He is hard working, utterly dependable and lifts the spirits of everyone he works with!</p>
            <p class="mb-2">Ife is the first person I turn to for a second opinion on frontend matters, his ability to cast a critical eye over a design and suggest meaningful ways to improve the UI & UX of the application has been a priceless tool for me over the years. He constantly strives to do his job in the best way possible as well as to help others to do theirs.</p>
            <p class="mb-2">I hope I get the opportunity to work with him in the future and I would absolutely recommend him to anyone in need of a frontend developer.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item">
  <div class="row m-0 testimonials-row">
    <div class="mid-line client-testimonials-line"></div>
    <div class="testimonial-card <%= @dark_mode ? 'dark-bg' : 'light-bg' %>">
      <div class="testimonial-image" style="background-image: url('https://avatars.githubusercontent.com/u/103648111?v=4')"></div>
      <div class="testimonial-content p-3">
        <h3 class="mb-1">Jette Handschumacher</h3>
        <h5 class="pb-0 pb-md-3 testimonial-role">CEO at Idego</h5>
        <div class="testimonial-message">
          <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote left-quote', alt: 'opening quote' %>
          <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote right-quote', alt: 'closing quote' %>
          <p class="mb-2">Working with Ife has been an absolute game-changer across several deeply impactful projects. From building a robust data tracking tool for Water Access Rwanda—a pioneering social enterprise improving access to clean water—to supporting The Clementine Project, a non-profit uplifting young women and single mothers in Rwanda, Ife has consistently brought excellence, innovation, and integrity to the table.</p>
          <p class="mb-2">Ife’s contributions have directly fuelled the success and growth of our projects, and I can confidently say that his presence elevates any initiative to new heights. He is not just a developer; he is a strategic thinker, a problem-solver, and a natural team player.</p>
          <p class="mb-2">I wholeheartedly recommend him for any project seeking real impact, technical excellence, and a spirit of teamwork that drives results.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item">
  <div class="row m-0 testimonials-row">
    <div class="mid-line client-testimonials-line"></div>
    <div class="testimonial-card <%= @dark_mode ? 'dark-bg' : 'light-bg' %>">
      <div class="testimonial-image" style="background-image: url('https://ca.slack-edge.com/T02NE0241-UHH6NURKN-0e34f6550bbd-192')"></div>
      <div class="testimonial-content p-3">
        <h3 class="mb-1">Tarek Rahme</h3>
        <h5 class="pb-0 pb-md-3 testimonial-role">Founder at Inventory Tracker App</h5>
        <div class="testimonial-message">
          <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote left-quote', alt: 'opening quote' %>
          <%= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote right-quote', alt: 'closing quote' %>
          <p class="mb-2">Working with Ife was an absolute pleasure and a true game-changer for our project. His expertise as a full-stack developer is evident in every part of the application, from the robust backend architecture to the flawlessly executed frontend.</p>
          <p class="mb-2">He doesn't just write code; he crafts intuitive and visually stunning user interfaces. Every element of the design felt intentional, demonstrating a deep understanding of user experience. He was a proactive partner, constantly thinking ahead and offering valuable insights that improved the final product immensely.</p>
          <p class="mb-2">He is a rare talent who combines technical proficiency with a keen eye for design. I highly recommend him to anyone looking for a developer who can deliver both a high-performing and beautifully designed application.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!--<div class="carousel-item">
  <div class="row m-0 testimonials-row">
    <div class="mid-line"></div>
    <div class="testimonial-card <%##= @dark_mode ? 'dark-bg' : 'light-bg' %>">
      <div class="testimonial-image" style="background-image: url('https://media-exp1.licdn.com/dms/image/C5603AQE_42-swxWlCw/profile-displayphoto-shrink_400_400/0/1540331575134?e=1632960000&v=beta&t=306erp3JMSZP1mbQSMhZULReelt9eET2xc5Ztmkkaf8')"></div>
      <div class="testimonial-content p-3">
        <h2>Ben Fanning</h2>
        <h4 class="pb-0 pb-md-3">Founder at Hoxton Digital</h4>
        <div class="testimonial-message">
          <%#= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote left-quote', alt: 'opening quote' %>
          <%#= image_tag "#{@dark_mode ? 'dark-quote.png' : 'quote.png'}", class: 'quote right-quote', alt: 'closing quote' %>
          <p>Ife was the first person I hired at Hoxton Digital and he is the first person I would hire if I started a new business tomorrow. He is hard working, utterly dependable and lifts the spirits of everyone he works with! Ife is the first person I turn to for a second opinion on frontend matters, his ability to cast a critical eye over a design and suggest meaningful ways to improve the UI & UX of the application has been a priceless tool for me over the years. He constantly strives to do his job in the best way possible as well as to help others to do theirs. I hope I get the opportunity to work with him in the future and I would absolutely recommend him to anyone in need of a frontend developer.</p>
        </div>
      </div>
    </div>
  </div>
</div>-->

app/views/pages/_project_modals.html.erb
<!-- FOENIX CODING -->


<div class="modal fade p-3 project" id="foenixCoding" tabindex="-1" aria-labelledby="foenixCodingLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="foenixCodingControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'foenix-coding-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'foenix-coding-2.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'foenix-coding-3.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'foenix-coding-4.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#foenixCodingControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#foenixCodingControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="foenixCodingLabel">Foenix Coding</h4>
          <p class="">Industrial Marking and Coding printers to print in high resolutions on every material.</p>
        </div>
      </div>
      <div class="modal-footer">
        <div>
          <%= link_to 'View Website', 'https://www.foenixcoding.com', class: 'primary-button', target: '_blank', rel: 'noopener'  %>
        </div>
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div>

<!-- THE NET -->

<div class="modal fade p-3 project" id="theNet" tabindex="-1" aria-labelledby="theNetLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="theNetControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'loop-beauty-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'loop-beauty-2.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'loop-beauty-3.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'loop-beauty-4.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#theNetControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#theNetControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="theNetLabel">LoopBeauty</h4>
          <p class="">Your destination for the best in beauty for women of colour. We partner with your favourite experts to curate the best in beauty products. Perfect your look in one place.</p>
        </div>
      </div>
      <div class="modal-footer">
        <div></div>
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div>

<!-- WATER ACCESS RWANDA -->

<div class="modal fade p-3 project" id="waterAccessRwanda" tabindex="-1" aria-labelledby="waterAccessRwandaLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="waterAccessRwandaControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'war-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'war-2.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'war-3.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#waterAccessRwandaControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#waterAccessRwandaControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="waterAccessRwandaLabel">Water Access Rwanda - Maintenance Tracker</h4>
          <p class="mb-0">We deploy innovative, capital-efficient and next-level services and systems to provide safe water to mainly rural and small town dwellers in Africa.</p>
        </div>
      </div>
      <div class="modal-footer">
        <div></div>
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div>

<!-- IDEGO -->

<div class="modal fade p-3 project" id="idego" tabindex="-1" aria-labelledby="idegoLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="idegoControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'idego-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'idego-2.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'idego-3.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'idego-4.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#idegoControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#idegoControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="idegoLabel">Idego</h4>
          <p class="">idego is a social impact accelerator that helps startups and aspiring businesses in Eastern Africa to benefit from digital transformation and our global network, and by that to develop their businesses in a sustainable way.</p>
        </div>
      </div>
      <div class="modal-footer">
        <div>
          <%= link_to 'View Website', 'http://idego.herokuapp.com/', class: 'primary-button', target: '_blank', rel: 'noopener'  %>
        </div>
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div>

<!-- THE CLEMENTINE PROJECT -->

<div class="modal fade p-3 project" id="theClementineProject" tabindex="-1" aria-labelledby="theClementineProjectLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="theClementineProjectControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'tcp-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'tcp-2.png', class: 'w-100' %>
            </div>
             <div class="carousel-item">
              <%= image_tag 'tcp-3.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#theClementineProjectControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#theClementineProjectControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="theClementineProjectLabel">The Clementine Project</h4>
          <p class="">Our project supports seamstresses in Rwanda to earn an independent and self-sufficient living.</p>
        </div>
      </div>
      <div class="modal-footer">
        <!--<div>-->
          <%#= link_to 'View Website', 'https://www.theclementineproject.de', class: 'primary-button', target: '_blank', rel: 'noopener'  %>
<!--        </div>-->
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div>

<!-- THE CLEMENTINE PROJECT -->

<div class="modal fade p-3 project" id="codebreakers" tabindex="-1" aria-labelledby="codebreakersLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div id="codebreakersControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'codebreakers-1.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-2.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-3.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-4.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-5.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-6.png', class: 'w-100' %>
            </div>
            <div class="carousel-item">
              <%= image_tag 'codebreakers-7.png', class: 'w-100' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#codebreakersControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#codebreakersControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true">
              <%= image_tag "#{@dark_mode ? 'dark-arrow.png' : 'arrow.png'}" %>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="pt-3 px-3 project-modal-info">
          <h4 class="modal-title mb-1" id="codebreakersLabel">Codebreakers</h4>
          <p class="mb-0">Complete coding challenges to level up your coding knowledge & win prizes! Suitable for beginners.</p>
        </div>
      </div>
      <div class="modal-footer">
        <div></div>
        <p class="modal-close" data-dismiss="modal">Close</p>
      </div>
    </div>
  </div>
</div> 

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container bottom-line h-100 <%= @dark_mode ? 'dark-border' : 'light-border' %>">
    <div class="d-flex justify-content-end align-items-center h-100">
      <div class="px-5 py-4">
        <h2 class="social-links"><%= mail_to 'ifeodugbesan@gmail.com', 'Email' %></h2>
        <h2 class="social-links"><%= link_to 'Github', 'https://github.com/ifeodugbesan', target: '_blank', rel: 'noopener' %></h2>
        <h2 class="social-links"><%= link_to 'LinkedIn', 'https://www.linkedin.com/in/ifeodugbesan', target: '_blank', rel: 'noopener' %></h2>
        <h2 class="social-links"><%= link_to 'Dribbble', 'https://dribbble.com/ifz10', target: '_blank', rel: 'noopener' %></h2>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="container top-line h-100 <%= @dark_mode ? 'dark-border' : 'light-border' %>">
    <div class="d-flex justify-content-center align-items-center w-100">
      <%= link_to switch_mode_path, method: :post do %>
        <div class="logo-flip">
          <div class="logo-flip-inner">
            <div class="logo-flip-front">
              <%= image_tag "#{@dark_mode ? 'dark-logo.png' : 'logo.png'}" %>
            </div>
            <div class="logo-flip-back">
               <%= image_tag "#{@dark_mode ? 'logo.png' : 'dark-logo.png'}" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>